// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/internal/migration (interfaces: ProviderConfigServicesGetter,ProviderConfigServices,ModelConfigService,ControllerCloudService)
//
// Generated by this command:
//
//	mockgen -typed -package migration -destination services_mock_test.go github.com/juju/juju/internal/migration ProviderConfigServicesGetter,ProviderConfigServices,ModelConfigService,ControllerCloudService
//

// Package migration is a generated GoMock package.
package migration

import (
	context "context"
	reflect "reflect"

	cloud "github.com/juju/juju/cloud"
	model "github.com/juju/juju/core/model"
	config "github.com/juju/juju/environs/config"
	gomock "go.uber.org/mock/gomock"
)

// MockProviderConfigServicesGetter is a mock of ProviderConfigServicesGetter interface.
type MockProviderConfigServicesGetter struct {
	ctrl     *gomock.Controller
	recorder *MockProviderConfigServicesGetterMockRecorder
}

// MockProviderConfigServicesGetterMockRecorder is the mock recorder for MockProviderConfigServicesGetter.
type MockProviderConfigServicesGetterMockRecorder struct {
	mock *MockProviderConfigServicesGetter
}

// NewMockProviderConfigServicesGetter creates a new mock instance.
func NewMockProviderConfigServicesGetter(ctrl *gomock.Controller) *MockProviderConfigServicesGetter {
	mock := &MockProviderConfigServicesGetter{ctrl: ctrl}
	mock.recorder = &MockProviderConfigServicesGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderConfigServicesGetter) EXPECT() *MockProviderConfigServicesGetterMockRecorder {
	return m.recorder
}

// ServicesForModel mocks base method.
func (m *MockProviderConfigServicesGetter) ServicesForModel(arg0 context.Context, arg1 model.UUID) (ProviderConfigServices, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServicesForModel", arg0, arg1)
	ret0, _ := ret[0].(ProviderConfigServices)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServicesForModel indicates an expected call of ServicesForModel.
func (mr *MockProviderConfigServicesGetterMockRecorder) ServicesForModel(arg0, arg1 any) *MockProviderConfigServicesGetterServicesForModelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServicesForModel", reflect.TypeOf((*MockProviderConfigServicesGetter)(nil).ServicesForModel), arg0, arg1)
	return &MockProviderConfigServicesGetterServicesForModelCall{Call: call}
}

// MockProviderConfigServicesGetterServicesForModelCall wrap *gomock.Call
type MockProviderConfigServicesGetterServicesForModelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderConfigServicesGetterServicesForModelCall) Return(arg0 ProviderConfigServices, arg1 error) *MockProviderConfigServicesGetterServicesForModelCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderConfigServicesGetterServicesForModelCall) Do(f func(context.Context, model.UUID) (ProviderConfigServices, error)) *MockProviderConfigServicesGetterServicesForModelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderConfigServicesGetterServicesForModelCall) DoAndReturn(f func(context.Context, model.UUID) (ProviderConfigServices, error)) *MockProviderConfigServicesGetterServicesForModelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockProviderConfigServices is a mock of ProviderConfigServices interface.
type MockProviderConfigServices struct {
	ctrl     *gomock.Controller
	recorder *MockProviderConfigServicesMockRecorder
}

// MockProviderConfigServicesMockRecorder is the mock recorder for MockProviderConfigServices.
type MockProviderConfigServicesMockRecorder struct {
	mock *MockProviderConfigServices
}

// NewMockProviderConfigServices creates a new mock instance.
func NewMockProviderConfigServices(ctrl *gomock.Controller) *MockProviderConfigServices {
	mock := &MockProviderConfigServices{ctrl: ctrl}
	mock.recorder = &MockProviderConfigServicesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderConfigServices) EXPECT() *MockProviderConfigServicesMockRecorder {
	return m.recorder
}

// Cloud mocks base method.
func (m *MockProviderConfigServices) Cloud() ControllerCloudService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cloud")
	ret0, _ := ret[0].(ControllerCloudService)
	return ret0
}

// Cloud indicates an expected call of Cloud.
func (mr *MockProviderConfigServicesMockRecorder) Cloud() *MockProviderConfigServicesCloudCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cloud", reflect.TypeOf((*MockProviderConfigServices)(nil).Cloud))
	return &MockProviderConfigServicesCloudCall{Call: call}
}

// MockProviderConfigServicesCloudCall wrap *gomock.Call
type MockProviderConfigServicesCloudCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderConfigServicesCloudCall) Return(arg0 ControllerCloudService) *MockProviderConfigServicesCloudCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderConfigServicesCloudCall) Do(f func() ControllerCloudService) *MockProviderConfigServicesCloudCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderConfigServicesCloudCall) DoAndReturn(f func() ControllerCloudService) *MockProviderConfigServicesCloudCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Config mocks base method.
func (m *MockProviderConfigServices) Config() ModelConfigService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(ModelConfigService)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockProviderConfigServicesMockRecorder) Config() *MockProviderConfigServicesConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockProviderConfigServices)(nil).Config))
	return &MockProviderConfigServicesConfigCall{Call: call}
}

// MockProviderConfigServicesConfigCall wrap *gomock.Call
type MockProviderConfigServicesConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderConfigServicesConfigCall) Return(arg0 ModelConfigService) *MockProviderConfigServicesConfigCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderConfigServicesConfigCall) Do(f func() ModelConfigService) *MockProviderConfigServicesConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderConfigServicesConfigCall) DoAndReturn(f func() ModelConfigService) *MockProviderConfigServicesConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockModelConfigService is a mock of ModelConfigService interface.
type MockModelConfigService struct {
	ctrl     *gomock.Controller
	recorder *MockModelConfigServiceMockRecorder
}

// MockModelConfigServiceMockRecorder is the mock recorder for MockModelConfigService.
type MockModelConfigServiceMockRecorder struct {
	mock *MockModelConfigService
}

// NewMockModelConfigService creates a new mock instance.
func NewMockModelConfigService(ctrl *gomock.Controller) *MockModelConfigService {
	mock := &MockModelConfigService{ctrl: ctrl}
	mock.recorder = &MockModelConfigServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelConfigService) EXPECT() *MockModelConfigServiceMockRecorder {
	return m.recorder
}

// ModelConfig mocks base method.
func (m *MockModelConfigService) ModelConfig(arg0 context.Context) (*config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelConfig", arg0)
	ret0, _ := ret[0].(*config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModelConfig indicates an expected call of ModelConfig.
func (mr *MockModelConfigServiceMockRecorder) ModelConfig(arg0 any) *MockModelConfigServiceModelConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelConfig", reflect.TypeOf((*MockModelConfigService)(nil).ModelConfig), arg0)
	return &MockModelConfigServiceModelConfigCall{Call: call}
}

// MockModelConfigServiceModelConfigCall wrap *gomock.Call
type MockModelConfigServiceModelConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelConfigServiceModelConfigCall) Return(arg0 *config.Config, arg1 error) *MockModelConfigServiceModelConfigCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelConfigServiceModelConfigCall) Do(f func(context.Context) (*config.Config, error)) *MockModelConfigServiceModelConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelConfigServiceModelConfigCall) DoAndReturn(f func(context.Context) (*config.Config, error)) *MockModelConfigServiceModelConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockControllerCloudService is a mock of ControllerCloudService interface.
type MockControllerCloudService struct {
	ctrl     *gomock.Controller
	recorder *MockControllerCloudServiceMockRecorder
}

// MockControllerCloudServiceMockRecorder is the mock recorder for MockControllerCloudService.
type MockControllerCloudServiceMockRecorder struct {
	mock *MockControllerCloudService
}

// NewMockControllerCloudService creates a new mock instance.
func NewMockControllerCloudService(ctrl *gomock.Controller) *MockControllerCloudService {
	mock := &MockControllerCloudService{ctrl: ctrl}
	mock.recorder = &MockControllerCloudServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControllerCloudService) EXPECT() *MockControllerCloudServiceMockRecorder {
	return m.recorder
}

// Cloud mocks base method.
func (m *MockControllerCloudService) Cloud(arg0 context.Context, arg1 string) (*cloud.Cloud, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cloud", arg0, arg1)
	ret0, _ := ret[0].(*cloud.Cloud)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cloud indicates an expected call of Cloud.
func (mr *MockControllerCloudServiceMockRecorder) Cloud(arg0, arg1 any) *MockControllerCloudServiceCloudCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cloud", reflect.TypeOf((*MockControllerCloudService)(nil).Cloud), arg0, arg1)
	return &MockControllerCloudServiceCloudCall{Call: call}
}

// MockControllerCloudServiceCloudCall wrap *gomock.Call
type MockControllerCloudServiceCloudCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerCloudServiceCloudCall) Return(arg0 *cloud.Cloud, arg1 error) *MockControllerCloudServiceCloudCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerCloudServiceCloudCall) Do(f func(context.Context, string) (*cloud.Cloud, error)) *MockControllerCloudServiceCloudCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerCloudServiceCloudCall) DoAndReturn(f func(context.Context, string) (*cloud.Cloud, error)) *MockControllerCloudServiceCloudCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
