// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/apiserver/facades/controller/charmrevisionupdater (interfaces: CharmhubRefreshClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	charmhub "github.com/juju/juju/charmhub"
	transport "github.com/juju/juju/charmhub/transport"
	reflect "reflect"
)

// MockCharmhubRefreshClient is a mock of CharmhubRefreshClient interface
type MockCharmhubRefreshClient struct {
	ctrl     *gomock.Controller
	recorder *MockCharmhubRefreshClientMockRecorder
}

// MockCharmhubRefreshClientMockRecorder is the mock recorder for MockCharmhubRefreshClient
type MockCharmhubRefreshClientMockRecorder struct {
	mock *MockCharmhubRefreshClient
}

// NewMockCharmhubRefreshClient creates a new mock instance
func NewMockCharmhubRefreshClient(ctrl *gomock.Controller) *MockCharmhubRefreshClient {
	mock := &MockCharmhubRefreshClient{ctrl: ctrl}
	mock.recorder = &MockCharmhubRefreshClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCharmhubRefreshClient) EXPECT() *MockCharmhubRefreshClientMockRecorder {
	return m.recorder
}

// Refresh mocks base method
func (m *MockCharmhubRefreshClient) Refresh(arg0 context.Context, arg1 charmhub.RefreshConfig) ([]transport.RefreshResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", arg0, arg1)
	ret0, _ := ret[0].([]transport.RefreshResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh
func (mr *MockCharmhubRefreshClientMockRecorder) Refresh(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockCharmhubRefreshClient)(nil).Refresh), arg0, arg1)
}
